import type { Meta, Players, Rules, Squad, Week } from "../contract/types";

export const meta: Meta = {
  contract_version: 1,
  generated_at: "2026-08-10T10:15:58.217761Z",
  run_id: "20260810T101557Z-d705a43f",
  git_sha: "14c97bc018cebb4fa8b7ac525097ca54d402af75",
  season: "2026/27",
  next_gameweek: 1,
  deadline_utc: "2026-08-21T17:30:00Z",
  horizon_gameweeks: 6,
  model: {
    name: "xp_v0",
    r_squared_on_price: 0.4943,
    price_dependence: "informative",
  },
  counts: { players: 2, teams: 20 },
};

export const rules: Rules = {
  contract_version: 1,
  season: "2026/27",
  source_snapshot_sha256: "abc",
  derived: {},
  squad: {
    size: 15,
    starting_size: 11,
    budget: 100.0,
    club_limit: 3,
    composition: { GKP: 2, DEF: 5, MID: 5, FWD: 3 },
    formation_min: { GKP: 1, DEF: 3, MID: 2, FWD: 1 },
    formation_max: { GKP: 1, DEF: 5, MID: 5, FWD: 3 },
    sell_on_fee: 0.5,
    sell_at_purchase_price: false,
  },
  scoring: {
    goals_scored: { GKP: 10, DEF: 6, MID: 5, FWD: 4 },
    assists: 3,
    clean_sheets: { GKP: 4, DEF: 4, MID: 1, FWD: 0 },
    defensive_contribution: { GKP: 0, DEF: 2, MID: 2, FWD: 2 },
  },
  transfers: { max_free_transfers: 5, extra_transfer_cost: -4 },
};

function components() {
  return {
    appearance: 1.8,
    goals: 0.5,
    assists: 0.2,
    clean_sheet: 1.0,
    goals_conceded: -0.3,
    saves: 0.0,
    defensive_contribution: 0.1,
    bonus: 0.2,
    cards: -0.1,
  };
}

export const players: Players = {
  contract_version: 1,
  players: [
    {
      id: 1,
      name: "Raya",
      full_name: "David Raya",
      position: "GKP",
      team: "ARS",
      team_id: 1,
      price: 6.0,
      xp_next: 4.199,
      xp_next_sd: 1.89,
      xp_horizon: 19.255,
      xp_horizon_sd: 8.665,
      start_probability: 0.938,
      confidence: "high",
      selected_by_percent: 31.0,
      status: "a",
      news: "",
      components: components(),
    },
    {
      id: 2,
      name: "Watkins",
      full_name: "Ollie Watkins",
      position: "FWD",
      team: "AVL",
      team_id: 2,
      price: 8.0,
      xp_next: 4.517,
      xp_next_sd: 2.033,
      xp_horizon: 22.214,
      xp_horizon_sd: 9.996,
      start_probability: 0.837,
      confidence: "high",
      selected_by_percent: 12.5,
      status: "a",
      news: "",
      components: components(),
    },
    {
      id: 3,
      name: "Mbeumo",
      full_name: "Bryan Mbeumo",
      position: "MID",
      team: "MUN",
      team_id: 16,
      price: 8.0,
      xp_next: 3.2,
      xp_next_sd: 1.5,
      xp_horizon: 15.0,
      xp_horizon_sd: 6.0,
      start_probability: 0.8,
      confidence: "medium",
      selected_by_percent: 20.0,
      status: "a",
      news: "",
      components: components(),
    },
  ],
};

export const squad: Squad = {
  contract_version: 1,
  run_id: "20260809T160802Z-c0972065",
  status: "optimal",
  objective: 231.322,
  solve_seconds: 0.512,
  total_price: 100.0,
  budget: 100.0,
  formation: { GKP: 1, DEF: 1, MID: 1, FWD: 1 },
  captain_id: 2,
  vice_captain_id: 1,
  bench_order: [3],
  players: [
    {
      player_id: 1,
      web_name: "Raya",
      position: "GKP",
      team: "ARS",
      team_id: 1,
      price: 6.0,
      xp_next: 4.199,
      xp_next_sd: 1.89,
      xp_horizon: 19.255,
      xp_horizon_sd: 8.665,
      start_probability: 0.938,
      confidence: "high",
      starting: true,
      is_captain: false,
      is_vice_captain: true,
      components: components(),
    },
    {
      player_id: 2,
      web_name: "Watkins",
      position: "FWD",
      team: "AVL",
      team_id: 2,
      price: 8.0,
      xp_next: 4.517,
      xp_next_sd: 2.033,
      xp_horizon: 22.214,
      xp_horizon_sd: 9.996,
      start_probability: 0.837,
      confidence: "high",
      starting: true,
      is_captain: true,
      is_vice_captain: false,
      components: components(),
    },
    {
      player_id: 3,
      web_name: "Mbeumo",
      position: "MID",
      team: "MUN",
      team_id: 16,
      price: 8.0,
      xp_next: 3.2,
      xp_next_sd: 1.5,
      xp_horizon: 15.0,
      xp_horizon_sd: 6.0,
      start_probability: 0.8,
      confidence: "medium",
      starting: false,
      is_captain: false,
      is_vice_captain: false,
      components: components(),
    },
  ],
};

/**
 * A week where one transfer is worth making.
 *
 * Deliberately includes a *losing* two-transfer option: the whole point of the panel is that every
 * option is shown with its own arithmetic, so a fixture with only the winner in it would let the
 * component drop the rest without a test noticing.
 */
export const week: Week = {
  contract_version: 1,
  run_id: "20260810T101557Z-d705a43f",
  skipped: false,
  deadline: {
    gameweek: 2,
    name: "Gameweek 2",
    // 18:30 BST on a Friday, which is 03:30 Saturday in Sydney — the case that motivated
    // rendering both zones at all.
    deadline_utc: "2026-08-28T17:30:00Z",
    decide_by_utc: "2026-08-28T05:30:00Z",
    local_zone: "Australia/Sydney",
    uk_zone: "Europe/London",
  },
  squad_state: {
    provenance: "declared",
    entry_id: 1234567,
    as_of_gameweek: null,
    bank: 0.5,
    sell_value: 99.5,
    budget: 100.0,
    free_transfers: 1,
    chips_used: [],
    warnings: ["squad declared by hand: no published picks are available"],
  },
  recommendation: {
    rationale: "1 free transfer(s) gain 2.40 expected points",
    is_roll: false,
    transfers: 1,
    hit_points: 0,
    net_expected_points: 52.4,
    gain_over_roll: 2.4,
    bank_after: 0.2,
    moves: [
      {
        out: { player_id: 1, web_name: "Salah", price: 14.5 },
        in: { player_id: 2, web_name: "Saka", price: 14.8 },
      },
    ],
    options: [
      { transfers: 0, hit_points: 0, net_expected_points: 50.0, gain_over_roll: 0, moves: [] },
      { transfers: 1, hit_points: 0, net_expected_points: 52.4, gain_over_roll: 2.4, moves: [] },
      { transfers: 2, hit_points: -4, net_expected_points: 49.1, gain_over_roll: -0.9, moves: [] },
    ],
    warnings: [],
  },
  advised: {
    gameweek: 2,
    squad: [1, 2, 3],
    starting: [1, 2],
    bench_order: [3],
    reserve_goalkeeper: null,
    captain: 2,
    vice_captain: 1,
    formation: "1-4-4-2",
    expected_points: 52.4,
  },
  alerts: [
    {
      severity: "urgent",
      category: "availability",
      message: "Salah is unavailable (injured): Hamstring",
      player_id: 1,
      detail: {},
    },
    {
      severity: "info",
      category: "price",
      message: "Saka is under pressure to rise",
      player_id: 2,
      detail: {},
    },
  ],
  reconciliation: null,
};

/** Preseason: no squad exists yet, which is normal rather than broken (DL-20). */
export const skippedWeek: Week = {
  contract_version: 1,
  run_id: "run-1",
  skipped: true,
  skipped_reason: "no published picks are available, and no squad is declared in configuration",
  deadline: week.deadline,
};
